on: [push]

jobs:
  create_draft_release:
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_draft_release.outputs.upload_url }}

    steps:
      - name: Create draft release on tags
        id: create_draft_release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

  latex-job:
    needs: create_draft_release
    runs-on: ubuntu-latest
    
    name: Compile And Upload PDF

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set git user
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions-bot@users.noreply.github.com
    
    - name: Define env
      run: |
        echo "GITHUB_TAG=$(git describe --always --tags)" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +'%Y_%m_%d')" >> $GITHUB_ENV

    - uses: actions/cache@v2
      name: Tectonic Cache
      with:
        path: ~/.cache/Tectonic
        key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
        restore-keys: |
          ${{ runner.os }}-tectonic-

    - uses: wtfjoke/setup-tectonic@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        biber-version: "latest"
 
    - name: Remove default font customizations
      run: sed -i.bak '12,14d' aom.tex

    - name: Prepare env
      run: |
        curl -Lo od.zip https://github.com/antijingoist/opendyslexic/releases/download/v0.91.12/opendyslexic-0.910.12-rc2-2019.10.17.zip
        unzip od.zip
        mkdir assets

    - name: Run Tectonic
      run: |
        tectonic aom.tex
        mv aom.pdf assets/aom-od.pdf

    - name: Upload PDF
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        path: assets/aom-od.pdf
        name: aom-od-${{ env.BUILD_DATE }}-${{ env.GITHUB_TAG }}.pdf
        if-no-files-found: error
    
    - name: Remove Open Dyslexic font customizations
      run: sed -i.bak '8,10d' aom.tex

    - name: Run Tectonic
      run: |
        tectonic aom.tex
        mv aom.pdf aom-std.pdf

    - name: Upload PDF
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        path: aom-std.pdf
        name: aom-std-${{ env.BUILD_DATE }}-${{ env.GITHUB_TAG }}.pdf
        if-no-files-found: error
    
    - name: Upload release assets
      if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
      id: upload-release-assets
      uses: dwenegar/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_draft_release.outputs.id }}
        assets_path: assets/
