on: [push]

jobs:
  latex-job:
    runs-on: ubuntu-latest
    
    name: Compile And Upload PDF

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cached Infra
      uses: actions/cache@v2
      env:
        cache-name: cached-tectonic
      with:
        path: |
          ~/.cache
        key: ${{ env.cache-name }}-${{ hashFiles('.cachefile') }}
        restore-keys: |
          ${{ env.cache-name }}-

    - name: Remove font customizations
      run: sed -i.bak '8,10d' aom.tex

    - name: LaTeX Compilation
      uses: vinay0410/tectonic-action@v1.1.2
      with:
        tex_path: 'aom.tex'
        push: 'no'
    
    - name: Upload PDF
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        path: aom.pdf
        name: aom.pdf
        if-no-files-found: error
